"""Standalone detector building blocks."""

from .hypotheses import PartitionScore, score_partition_agreement, search_orientation_and_phase
from .search import (
    DECISION_RULE,
    FORWARD,
    ORIENTATIONS,
    REVERSE_COMPLEMENT,
    Calibration,
    DetectionResult,
    DetectorConfig,
    DetectorHypothesis,
    PartitionCache,
    WindowedDetectionResult,
    WindowedHypothesis,
    WindowedSearchConfig,
    calibrate_threshold,
    detect,
    detect_aligned,
    detect_windowed,
    detection_rate,
    empirical_p_value,
    enumerate_search,
    standardized_agreement,
)

__all__ = [
    "DECISION_RULE",
    "FORWARD",
    "ORIENTATIONS",
    "REVERSE_COMPLEMENT",
    "Calibration",
    "DetectionResult",
    "DetectorConfig",
    "DetectorHypothesis",
    "PartitionCache",
    "PartitionScore",
    "WindowedDetectionResult",
    "WindowedHypothesis",
    "WindowedSearchConfig",
    "calibrate_threshold",
    "detect",
    "detect_aligned",
    "detect_windowed",
    "detection_rate",
    "empirical_p_value",
    "enumerate_search",
    "score_partition_agreement",
    "search_orientation_and_phase",
    "standardized_agreement",
]
